In [1]:
import pandas as pd
import datetime
import numpy as np
from dateutil.relativedelta import relativedelta

## CDI

In [2]:
df = pd.read_excel("datalake_files/DCF - RP'22 8&04 - Valores.xlsx",sheet_name = 'Budget',header = 5)
df = df.loc[~df['Unnamed: 1'].isnull()].drop('Unnamed: 0',axis = 1).set_index('Unnamed: 1').T
df.columns.name = None
df = df[list(map(lambda x: type(x) == datetime.datetime,df.index.values))]
serie = df['Cash Accumulated Available'] * 100

In [39]:
def composed_interest(days,values):
    results = [values[0] + 1]
    for day,valor in zip(days[1:],values[1:]):
        if day == 0:
            results.append(1)
        else:
            results.append(results[-1] * valor + 1)
    return np.array(results) - 1

In [41]:
arquivo = 'datalake_files/09 Debt vs Setembro 2022 - RP - Budget 2023.xlsx'
dfs = []
messages = []
for i in range(1,11):
    try:
        df = pd.read_excel(arquivo,sheet_name = f'{i}ª Emissão CDI',header = 4)
        df = df[df['Filtro'] == 'X'][['Data','Last  CDI','Days','Interest (Month)','Principal Balance']].dropna()
        df['Data'] = pd.to_datetime(df['Data'],format = '%d%m%Y')
        if df['Data'].iloc[0] < datetime.datetime.now():
            df['Last  CDI'] = df['Last  CDI'] / 100
            spread = pd.read_excel(arquivo,sheet_name = '1ª Emissão CDI').iloc[2,9] / 100
            df['Taxa Diária Estimada'] = ((df['Last  CDI'] + float(spread) + 1) ** (1/252)) - 1
            df['Days Dif'] = df['Days'].diff().fillna(df['Days'].iloc[0]).apply(lambda x: 0 if x < 2 else x)
            df['Taxa Estimada Período'] = ((1 + df['Taxa Diária Estimada']) ** df['Days Dif']) - 1
            df['Taxa Acumulada Estimada'] = composed_interest(df['Days Dif'].values,df['Taxa Estimada Período'].values)
            df['Juros Estimados'] = df['Principal Balance'] * df['Taxa Acumulada Estimada']
            df['Despesa Estimada'] = df['Juros Estimados'].cumsum()
            df['Despesa Real'] = (df['Interest (Month)'] * df['Days Dif'].apply(lambda x: 0 if x == 0 else 1)).cumsum()
            df['Erro'] = 100 * (df['Despesa Real'] - df['Despesa Estimada']) / df['Despesa Real']
            dfs.append(df)
            messages.append(f'{i}ª Emissão CDI: Sucesso')
        else:
            messages.append(f'{i}ª Emissão CDI: Não Realizado')
    except ValueError as e:
        print(e)
        messages.append(f'{i}ª Emissão CDI: ' + str(e))

Worksheet named '9ª Emissão CDI' not found
Worksheet named '10ª Emissão CDI' not found

In [42]:
dfs[0]

,Data,Last CDI,Days,Interest (Month),Principal Balance,Taxa Diária Estimada,Days Dif,Taxa Estimada Período,Taxa Acumulada Estimada,Juros Estimados,Despesa Estimada,Despesa Real,Erro
18,2018-06-30,0.0639,4,275916.96,240000000.0,0.000285,4,0.00114,0.001140,2.735362e+05,2.735362e+05,275916.96,0.862852
49,2018-07-31,0.0639,25,1453780.80,240000000.0,0.000285,21,0.005998,0.006005,1.441188e+06,1.714724e+06,1729697.76,0.865668
80,2018-08-31,0.0639,48,1602332.40,240000000.0,0.000285,23,0.006571,0.006611,1.586567e+06,3.301291e+06,3332030.16,0.922523
110,2018-09-30,0.0639,68,1401960.48,240000000.0,0.000285,20,0.005712,0.005749,1.379864e+06,4.681156e+06,4733990.64,1.116080
141,2018-10-31,0.064,89,1482667.68,240000000.0,0.000285,21,0.006006,0.006040,1.449707e+06,6.130863e+06,6216658.32,1.380089
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1762,2023-03-31,0.119,74,1388511.60,120000000.0,0.000483,23,0.011176,0.011275,1.353003e+06,7.289528e+07,74783799.60,2.525302
1792,2023-04-30,0.119,93,1158834.24,120000000.0,0.000483,19,0.009224,0.009328,1.119328e+06,7.401461e+07,75942633.84,2.538790
1823,2023-05-31,0.119,114,1293370.56,120000000.0,0.000483,21,0.0102,0.010295,1.235367e+06,7.524998e+07,77236004.40,2.571375
1838,2023-06-15,0.119,124,620561.52,120000000.0,0.000483,10,0.004844,0.004894,5.872687e+05,7.583725e+07,77856565.92,2.593641
1839,2023-06-15,0.119,0,7573870.56,120000000.0,0.000483,0,0.0,0.000000,0.000000e+00,7.583725e+07,77856565.92,2.593641

## IPCA

In [14]:
df = pd.read_excel('datalake_files/09 Debt vs Setembro 2022 - RP - Budget 2023.xlsx',sheet_name = '1ª Emissão IPCA',header = 6).drop(['Unnamed: 0','Unnamed: 2'],axis = 1)
df = df[df['Filtro'] == 'X']
df

1ª Emissão CDI
1ª Emissão IPCA
2ª Emissão CDI
2ª Emissão IPCA
#REF
3ª Emissão CDI
#REF
#REF
#REF
#REF
#REF
#REF
#REF
#REF
#REF
MUFG 2nd Contract
#REF
#REF
#REF
#REF
#REF

,Date,IPCA,Month,Ref,Days,Days.1,Daily Index,Accumulated Index,Nominal Value,NV + IPCA,...,Interest- R$,Price (UNIT),Interest (Unit),Interest,MV (Unit),Monetary Variation,Principal + Interest + MV,Principal Balance,Filtro,Diferença
23,2018-05-31,4961.84,1.002200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0,0.000000e+00,0.00000,0.0,0.000000e+00,2.400000e+08,X,NaN
53,2018-06-30,5044.46,1.012600,1.0,4.0,21.0,1.002388,1.002388,1000.0,1002.38787,...,0.950751,1003.338621,0.950751,2.281804e+05,2.38787,573088.8,2.408013e+08,2.405731e+08,X,NaN
84,2018-07-31,5061.11,1.003301,2.0,11.0,22.0,1.001649,1.010045,1000.0,1010.04533,...,6.002518,1016.047848,5.051767,1.212424e+06,7.65746,1837790.4,2.438515e+08,2.424109e+08,X,NaN
115,2018-08-31,5056.56,0.999101,3.0,12.0,22.0,0.999510,1.011215,1000.0,1011.21464,...,11.569714,1022.784354,5.567196,1.336127e+06,1.16931,280634.4,2.454682e+08,2.426915e+08,X,NaN
145,2018-09-30,5080.83,1.004800,4.0,10.0,19.0,1.002523,1.013352,1000.0,1013.35185,...,16.464134,1029.815984,4.89442,1.174661e+06,2.13721,512930.4,2.471558e+08,2.432044e+08,X,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2611,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,500,1.200000e+08,NaN,NaN,NaN,-8.940697e-08,X,NaN
2621,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,TOTAL JUROS,1.133585e+08,NaN,NaN,NaN,NaN,X,NaN
2622,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,TOTAL CM,9.896568e+07,NaN,NaN,NaN,NaN,X,NaN
2623,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,TOTAL PRINCIPAL,2.400000e+08,NaN,NaN,NaN,NaN,X,NaN
2624,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,TOTAL GERAL,4.523242e+08,NaN,NaN,NaN,NaN,X,NaN

## Câmbio

In [13]:
df = pd.read_excel('datalake_files/09 Debt vs Setembro 2022 - RP - Budget 2023.xlsx',sheet_name = 'Daily Calculation prop2019',header = 2)
df = df[['Date','USD','Repayment']].dropna()
df = df.set_index('Date')
df = df[datetime.datetime.today():]
df['Period'] = df.index.to_period('m')
df['Reais_Acumulado'] = (df['USD'] * df['Repayment']).cumsum()